databases:
  - name: fortune
    databaseName: fortune
    user: fortune

services:
  - type: web
    name: fortune
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fortune
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false