# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34a55d4870e616494531080d5df5c970d97b35ba36df58f2a7963f5f6c709a1662463f3fa86a9015c51e01ed7f065e1a0164979e52e00713789bbd9eb1db5d10

test:
  secret_key_base: 3189772ceefa3b62d30e17639a2750a99be249694a84ac2c8719eaff6fd435f2aa5d61e3f8af5fb45e82b3eb3a6353ab02b629f1707d4fa955b60962d0414d41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
