# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Fortune.create(fortune: %s(Today it's up to you to create the peacefulness you long for.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(A friend asks only for your time not your money.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(If you refuse to accept anything but the best, you very often get it.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(A smile is your passport into the hearts of others.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(A good way to keep healthy is to eat more Chinese food.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(Your high-minded principles spell success.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(Hard work pays off in the future, laziness pays off now.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(Change can hurt, but it leads a path to something better.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(Enjoy the good luck a companion brings you.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(People are naturally attracted to you.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(Hidden in a valley beside an open stream- This will be the type of place where you will find your dream.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(A chance meeting opens new doors to success and friendship.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(You learn from your mistakes... You will learn a lot today.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(If you have something good in your life, don't let it go!), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(What ever you're goal is in life, embrace it visualize it, and for it will be yours.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(Your shoes will make you happy today.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(You cannot love life until you live the life you love.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(Be on the lookout for coming events; They cast their shadows beforehand.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(Land is always on the mind of a flying bird.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(The man or woman you desire feels the same about you.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(Meeting adversity well is the source of your strength.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(A dream you have will come true.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(Our deeds determine us, as much as we determine our deeds.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(Never give up. You're not a failure if you don't give up.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(You will become great if you believe in yourself.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(There is no greater pleasure than seeing your loved ones prosper.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(You will marry your lover.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(A very attractive person has a message for you.), author: "http://www.fortunecookiemessage.com/archive.php")
Fortune.create(fortune: %s(I'm afraid for the calendar. Its days are numbered.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(My wife said I should do lunges to stay in shape. That would be a big step forward.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why do fathers take an extra pair of socks when they go golfing?" "In case they get a hole in one!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do a tick and the Eiffel Tower have in common?" "They're both Paris sites.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do you call a fish wearing a bowtie?" "Sofishticated.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How do you follow Will Smith in the snow?" "You follow the fresh prints.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(If April showers bring May flowers, what do May flowers bring?" "Pilgrims.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do you call a factory that makes okay products?" "A satisfactory.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Dear Math, grow up and solve your own problems.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What did the janitor say when he jumped out of the closet?" "Supplies!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Have you heard about the chocolate record player? It sounds pretty sweet.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What did the ocean say to the beach?" "Nothing, it just waved.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why do seagulls fly over the ocean?" "Because if they flew over the bay, we'd call them bagels.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I only know 25 letters of the alphabet. I don't know y.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How does the moon cut his hair?" "Eclipse it.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What did one wall say to the other?" "I'll meet you at the corner.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What did the zero say to the eight?" "That belt looks good on you.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(A skeleton walks into a bar and says, 'Hey, bartender. I'll have one beer and a mop.'),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Where do fruits go on vacation?" "Pear-is!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I asked my dog what's two minus two. He said nothing.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What did Baby Corn say to Mama Corn?" "Where's Pop Corn?),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What's the best thing about Switzerland?" "I don't know, but the flag is a big plus.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What does a sprinter eat before a race?" "Nothing, they fast!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Where do you learn to make a banana split?" "Sundae school.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What has more letters than the alphabet?" "The post office!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Dad, did you get a haircut?" "No, I got them all cut!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do you call a poor Santa Claus?" "St. Nickel-less.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I got carded at a liquor store, and my Blockbuster card accidentally fell out. The cashier said never mind.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Where do boats go when they're sick?" "To the boat doc.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I don't trust those trees. They seem kind of shady.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How do you get a squirrel to like you? Act like a nut.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why don't eggs tell jokes? They'd crack each other up.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I don't trust stairs. They're always up to something.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do you call someone with no body and no nose? Nobody knows.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Did you hear the rumor about butter? Well, I'm not going to spread it!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why couldn't the bicycle stand up by itself? It was two tired.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What did one hat say to the other?" "Stay here! I'm going on ahead.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why did Billy get fired from the banana factory? He kept throwing away the bent ones.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Dad, can you put my shoes on?" "No, I don't think they'll fit me.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why can't a nose be 12 inches long? Because then it would be a foot.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What does a lemon say when it answers the phone?" "Yellow!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(This graveyard looks overcrowded. People must be dying to get in.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What kind of car does an egg drive?" "A yolkswagen.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Dad, can you put the cat out?" "I didn't know it was on fire.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How do you make 7 even?" "Take away the s.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How does a taco say grace?" "Lettuce pray.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What time did the man go to the dentist? Tooth hurt-y.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why didn't the skeleton climb the mountain?" "It didn't have the guts.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do you call it when a snowman throws a tantrum?" "A meltdown.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How many tickles does it take to make an octopus laugh? Ten tickles.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I have a joke about chemistry, but I don't think it will get a reaction.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What concert costs just 45 cents? 50 Cent featuring Nickelback!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What does a bee use to brush its hair?" "A honeycomb!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How do you make a tissue dance? You put a little boogie in it.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why did the math book look so sad? Because of all of its problems!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do you call cheese that isn't yours? Nacho cheese.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(My dad told me a joke about boxing. I guess I missed the punch line.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What kind of shoes do ninjas wear? Sneakers!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How does a penguin build its house? Igloos it together.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How did Harry Potter get down the hill?" "Walking. JK! Rowling.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Best One-Liner Dad Jokes
Fortune.create(fortune: %s(I used to be addicted to soap, but I'm clean now.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(A guy walks into a bar...and he was disqualified from the limbo contest.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(You think swimming with sharks is expensive? Swimming with sharks cost me an arm and a leg.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(When two vegans get in an argument, is it still called a beef?),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I ordered a chicken and an egg from Amazon. I'll let you know...),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Do you wanna box for your leftovers?" "No, but I'll wrestle you for them.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(That car looks nice but the muffler seems exhausted.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Shout out to my fingers. I can count on all of them.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(If a child refuses to nap, are they guilty of resisting a rest?),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What country's capital is growing the fastest?" "Ireland. Every day it's Dublin.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I once had a dream I was floating in an ocean of orange soda. It was more of a fanta sea.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Did you know corduroy pillows are in style? They're making headlines.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Did you hear about the kidnapping at school? It's okay, he woke up.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(A cheeseburger walks into a bar. The bartender says, 'Sorry, we don't serve food here.'),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I once got fired from a canned juice company. Apparently I couldn't concentrate.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I used to play piano by ear. Now I use my hands.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Have you ever tried to catch a fog? I tried yesterday but I mist.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I'm on a seafood diet. I see food and I eat it.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why did the scarecrow win an award? Because he was outstanding in his field.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I made a pencil with two erasers. It was pointless.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How do you make a Kleenex dance? Put a little boogie in it!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I'm reading a book about anti-gravity. It's impossible to put down!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Did you hear about the guy who invented the knock-knock joke? He won the 'no-bell' prize.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I've got a great joke about construction, but I'm still working on it.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I used to hate facial hair...but then it grew on me.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I decided to sell my vacuum cleaner—it was just gathering dust!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I had a neck brace fitted years ago and I've never looked back since.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(You know, people say they pick their nose, but I feel like I was just born with mine.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What's brown and sticky? A stick.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why can't you hear a psychiatrist using the bathroom? Because the 'P' is silent.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do you call an elephant that doesn't matter? An irrelephant.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do you get from a pampered cow? Spoiled milk.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I like telling Dad jokes. Sometimes he laughs!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What's the best smelling insect?" "A deodor-ant.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I used to be a personal trainer. Then I gave my too weak notice.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Did I tell you the time I fell in love during a backflip? I was heels over head!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(If a child refuses to sleep during nap time, are they guilty of resisting a rest?),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I ordered a chicken and an egg online. I’ll let you know.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(It takes guts to be an organ donor.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(If you see a crime at an Apple Store, does that make you an iWitness?),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I'm so good at sleeping, I can do it with my eyes closed!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I was going to tell a time-traveling joke, but you guys didn't like it.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Best Dad Joke Puns
Fortune.create(fortune: %s(What do you call a fake noodle?" "An impasta." 
Fortune.create(fortune: %s(What do you call a belt made of watches?" "A waist of time.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What happens when a strawberry gets run over crossing the street?" "Traffic jam.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do you call two monkeys that share an Amazon account?" "Prime mates.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do you call a pony with a sore throat?" "A little hoarse.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Where do math teachers go on vacation?" "Times Square.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Whenever I try to eat healthy, a chocolate bar looks at me and Snickers.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What does garlic do when it gets hot?" "It takes its cloves off.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What's a robot's favorite snack?" "Computer chips.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How much does it cost Santa to park his sleigh?" "Nothing, it's on the house.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Mountains aren't just funny. They're hill areas.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do clouds wear?" "Thunderwear.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why are piggy banks so wise?" "They're filled with common cents.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why is Peter Pan always flying?" "He neverlands.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How do you get a good price on a sled?" "You have toboggan.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How can you tell if a tree is a dogwood tree?" "By its bark.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I used to hate facial hair, but then it grew on me.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(It's inappropriate to make a 'dad joke' if you're not a dad. It's a faux pa.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do you call a hot dog on wheels?" "Fast food!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Where do young trees go to learn?" "Elementree school.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Did you hear about the circus fire? It was in tents.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Can February March? No, but April May!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(How do lawyers say goodbye? We'll be suing ya!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Wanna hear a joke about paper? Never mind—it's tearable.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What's the best way to watch a fly fishing tournament? Live stream.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Spring is here! I got so excited I wet my plants.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I could tell a joke about pizza, but it's a little cheesy.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Don't trust atoms. They make up everything!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(When does a joke become a dad joke? When it becomes apparent.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I wouldn't buy anything with velcro. It's a total rip-off.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What’s an astronaut’s favorite part of a computer? The space bar.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(I don't play soccer because I enjoy the sport. I'm just doing it for kicks!),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why are elevator jokes so classic and good? They work on many levels.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Why do bees have sticky hair? Because they use a honeycomb.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What do you call a fake noodle? An impasta.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Which state has the most streets? Rhode Island.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What did the coffee report to the police? A mugging.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(What did the fish say when he hit the wall? Dam.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(Is this pool safe for diving? It deep ends.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
Fortune.create(fortune: %s(If you see a crime happen at the Apple store, what does it make you?" "An iWitness.),author: "https://www.countryliving.com/life/a27452412/best-dad-jokes/")
